export const SET_COLLAPSED = "SET_COLLAPSED"
export const TOGGLE_COLLAPSED = "TOGGLE_COLLAPSED"
export const EXPAND_ALL = "EXPAND_ALL"
export const COLLAPSE_ALL = "COLLAPSE_ALL"

export const SET_SECTION_FILTERS = "SET_SECTION_FILTERS"
export const SET_TECH_FILTERS = "SET_TECH_FILTERS"
export const SET_TECH_ORDER = "SET_TECH_ORDER"
